# Wallpaper setup!

splash = false

wallpaper {
	monitor = HDMI-A-1
	path = /home/fluffyn/.wallpapers/retro_1.png
	fit_mode = cover
}

wallpaper {
	monitor = eDP-1
	path = /home/fluffyn/.wallpapers/retro_2.png
	fit_mode = cover
}
